import Footer from "../components/footer/Footer";
import Navbar from "../components/navbar/Navbar";
import { ThemeProvider } from "../context/ThemeContext";
import "./globals.css";
import { Inter, Nunito, Bebas_Neue } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({subsets: ["latin"]})

export const metadata = {
  title: "Portfolio Bastien Autem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ThemeProvider>
          <div className="container">
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
